m2.c 1: 
m2.c 2: 
m2.c 3: 
m2.c 4: 
m2.c 5: 
m2.c 6: 
m2.c 7: 
m2.c 8: 
m2.c 9: 
m2.c 10: 
m2.c 11: 
m2.c 12: main()
m2.c 13: {
m2.c 14: int i,j;
m2.c 15: clrscr();
m2.c 16: 
m2.c 17: {       for(i=1;i<6;i++)	{	for(j=i;j<6;j++)	    printf(" "); for(j=1;j<=i;j++)	printf("%c",'*');	  printf("\n");		}   } ;
m2.c 18: {       for(i=1;i<5;i++)	{	for(j=i;j<5;j++)	    printf(" "); for(j=1;j<=i;j++)	printf("%c",'#');	  printf("\n");		}   } ;
m2.c 19: getch();
m2.c 20: }
m2.c 21: 
m2.c 22: 